version: "3"

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: ecommercesite
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:

# -------------------------------------------------------------------
# version: '3'

# services:
#   django_gunicorn:
#     volumes:
#       - static:/static
#     build:
#       context: .
#     ports:
#       - "8000:8000"
#   nginx:
#     build: .
#     volumes:
#       - static:/static
#     ports:
#       - "80:80"
#     depends_on:
#       - django_gunicorn

# volumes:
#   static:





# https://learndjango.com/tutorials/django-docker-and-postgresql-tutorial
# python manage.py migrate
# python manage.py collectstatic
# gunicorn OnlineShopping.EcommerceSite.EcommerceSite
